# This files generates all intermediate files and combine them into one executatble file



# Syntax: make   OR
#         make all


# to remove all intermediate files
# Syntax: make clean

# compiler to be used. Here it is 'gcc'.
$(CC) = gcc

# default target which will be executed at first by default
all: BC


# BC is name given for executables that will be generated by command mentioned below.
# Infix2Postfix.o eval_postfix.o calc.o main.o files are its dependencies

BC: CDLL.o Infix2Postfix.o eval_postfix.o calc.o main.o
	$(CC) CDLL.o Infix2Postfix.o eval_postfix.o calc.o main.o -o BC

CDLL.o: CDLL.c
	$(CC) -c CDLL.c

Infix2Postfix.o: Infix2Postfix.c
	$(CC) -c Infix2Postfix.c

eval_postfix.o: eval_postfix.c 
	$(CC) -c eval_postfix.c

calc.o: calc.c  
	$(CC) -c calc.c

main.o: main.c CDLL.h
	$(CC) -c main.c


# target to clean / remove all intermediate and executables files generated 
clean:
	rm -rf *.o BC